try:
  pass
except Exception:
  pass
else:
  pass
finally:
  pass

# Exception is a general catch all catch, it wont tell you anything specific if you dont know 
# what the error is. It is better to create your own error handling module